# Generated by Django 3.2.2 on 2021-05-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210517_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
