# Generated by Django 3.2.2 on 2021-05-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published Video', 'verbose_name_plural': 'Published Videos'},
        ),
    ]
