# Generated by Django 3.2.2 on 2021-05-16 19:08

from django.db import migrations, models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=False, upload_to='static/videos', validators=[videos.validators.file_validator]),
        ),
    ]
