# Generated by Django 3.2.2 on 2021-05-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAllProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All Video',
                'verbose_name_plural': 'All Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
